package:
  name: filebeat
  version: 8.12.0
  epoch: 0
  description: Filebeat is an open source file harvester, mostly used to fetch logs files and feed them into logstash
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - tini

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go-fips
      - make
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/elastic/beats
      tag: v${{package.version}}
      expected-commit: 27c592782c25906c968a41f0a6d8b1955790c8c5

  - runs: |
      cd filebeat
      export GOBIN="$GOPATH/bin"
      export PATH=$PATH:$GOPATH/bin
      go install github.com/mitchellh/gox@latest
      OS=$(go env GOOS)
      ARCH=$(go env GOARCH)
      make GOX_OS=$OS GOX_FLAGS=-arch="$ARCH" crosscompile

      mkdir -p "${{targets.destdir}}"/usr/share/filebeat
      mkdir -p "${{targets.destdir}}"/usr/local/bin
      mkdir -p "${{targets.destdir}}"/usr/share/filebeat/modules.d

      mv build/bin/filebeat-$OS-$ARCH "${{targets.destdir}}"/usr/share/filebeat/filebeat

      mkdir -p "${{targets.destdir}}"/usr/share/filebeat/data "${{targets.destdir}}"/usr/share/filebeat/logs

      chown -R root:root "${{targets.destdir}}"/usr/share/filebeat && \
        find "${{targets.destdir}}"/usr/share/filebeat -type d -exec chmod 0755 {} \; && \
        find "${{targets.destdir}}"/usr/share/filebeat -type f -exec chmod 0644 {} \; && \
        chmod 0755 "${{targets.destdir}}"/usr/share/filebeat/filebeat && \
        chmod 0775 "${{targets.destdir}}"/usr/share/filebeat/modules.d && \
        chmod 0775 "${{targets.destdir}}"/usr/share/filebeat/data "${{targets.destdir}}"/usr/share/filebeat/logs

      sed -i 's/{{ \.BeatName }}/replacement_text/g' ../dev-tools/packaging/templates/docker/docker-entrypoint.tmpl > "${{targets.destdir}}"/usr/local/bin/docker-entrypoint
      chmod 755 "${{targets.destdir}}"/usr/local/bin/docker-entrypoint

  - uses: strip

update:
  enabled: true
  github:
    strip-prefix: v
    identifier: elastic/beats
