package:
  name: fluent-plugin-splunk-hec
  version: 1.3.2
  epoch: 1
  description: This is the Fluentd output plugin for sending events to Splunk via HEC
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

pipeline:
  - uses: fetch
    with:
      expected-sha256: 102979e591268531d6df9b60920c3ee8480ed5a2e35b85a54a33d47b8a289859
      uri: https://github.com/splunk/fluent-plugin-splunk-hec/archive/refs/tags/${{package.version}}.tar.gz

  - uses: ruby/build
    with:
      gem: ${{package.name}}

  - uses: ruby/install
    with:
      gem: ${{package.name}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: splunk/fluent-plugin-splunk-hec
