package:
  name: kayenta-2.46
  version: "2.46.0"
  epoch: 0
  description: Automated Canary Service
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-17-jre

environment:
  contents:
    packages:
      - busybox
      - openjdk-17
      - openjdk-17-default-jvm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/spinnaker/kayenta
      expected-commit: a69573be9d8fededacf80817e4151a2c8df41276
      tag: v${{package.version}}

  - uses: auth/gradle

  - uses: patch
    with:
      patches: upgrade-dependencies.patch

  - runs: |
      export GRADLE_OPTS="-Dorg.gradle.daemon=false -Xmx2g -Xms2g"
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      ./gradlew --info --stacktrace build kayenta-web:installDist \
          -x :kayenta-core:test \
          -x :kayenta-integration-tests:test

      mkdir -p ${{targets.contextdir}}/opt/kayenta
      cp -r kayenta-web/build/install/kayenta/* ${{targets.contextdir}}/opt/kayenta

test:
  environment:
    contents:
      packages:
        - jq
        - redis
        - curl
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
  pipeline:
    - uses: test/daemon-check-output
      with:
        setup: |
          redis-server > /tmp/redis.logs 2>&1 &
          sleep 2
        start: /opt/kayenta/bin/kayenta
        timeout: 120
        expected_output: |
          Started Main
          Tomcat started
        post: |
          sleep 5 # Allow some time for the service to start
          # Test health endpoint
          echo "Testing /health endpoint:"
          HEALTH_OUTPUT=$(curl -s -X GET http://localhost:8090/health)
          # Verify health status is UP
          STATUS=$(echo "$HEALTH_OUTPUT" | jq -r '.status')
          [ "$STATUS" = "UP" ] || { echo "Expected health status UP, got: $STATUS"; exit 1; }

update:
  enabled: true
  github:
    identifier: spinnaker/kayenta
    strip-prefix: v
    tag-filter: v2.46.
