package:
  name: pgvector
  version: 0.6.0
  epoch: 0
  description: Open-source vector similarity search for PostgreSQL
  copyright:
    - license: PostgreSQL

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - postgresql-dev


pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pgvector/pgvector
      expected-commit: 281d4fcf60e2f037fa09d62be2543bb4d7511f2b
      tag: v${{package.version}}

  - runs: |
      make OPTFLAGS=""
      make USE_PGXS=1 DESTDIR="${{targets.destdir}}" PG_CONFIG=/usr/bin/pg_config install

  - uses: strip

update:
  enabled: true
  github:
    identifier: pgvector/pgvector
    strip-prefix: v
    use-tag: true
