package:
  name: wordpress
  version: 6.5.4
  epoch: 0
  description: "The Open Source Publishing Platform"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - php

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wordpress/wordpress
      tag: ${{package.version}}
      expected-commit: e67e9caef43512751aae60f37d91cf589dce78b0
      destination: "${{targets.destdir}}/usr/share/wordpress"

update:
  enabled: true
  github:
    identifier: wordpress/wordpress
    use-tag: true
